plugins {
    id 'com.android.library'
    alias libs.plugins.android.junit5
}

android {
    compileSdkVersion libs.versions.compile.sdk.version.get()
    namespace = 'org.twinlife.twinme.android'

    buildFeatures {
        buildConfig = true
    }
    defaultConfig {
        minSdkVersion libs.versions.min.sdk.version.get() as int
        targetSdkVersion libs.versions.target.sdk.version.get() as int
        buildConfigField "String", "VERSION", '"1.0.0"'

        // Flavor-specific fields, disabled by default, enabled for the appropriate flavors.
        buildConfigField 'boolean', 'IS_TWINME', 'false'
        buildConfigField 'boolean', 'IS_SKRED', 'false'
        buildConfigField 'boolean', 'IS_PLUS', 'false'
        buildConfigField 'boolean', 'IS_GOOGLE', 'false'
        buildConfigField 'boolean', 'IS_HUAWEI', 'false'

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        testInstrumentationRunnerArguments["runnerBuilder"] = "de.mannodermaus.junit5.AndroidJUnit5Builder"
    }

    flavorDimensions = ["product", "tier", "distribution"]

    productFlavors {
        twinme {
            dimension "product"
            // Define constant booleans so the compiler optimizes flavor-specific code away.
            buildConfigField 'boolean', 'IS_TWINME', 'true'
        }
        skred {
            dimension "product"
            buildConfigField 'boolean', 'IS_SKRED', 'true'
        }

        free {
            dimension "tier"
        }
        '+' {
            dimension "tier"
            buildConfigField 'boolean', 'IS_PLUS', 'true'
        }

        google {
            dimension "distribution"
            buildConfigField 'boolean', 'IS_GOOGLE', 'true'
        }
        huawei {
            dimension "distribution"
            buildConfigField 'boolean', 'IS_HUAWEI', 'true'
        }
        universal {
            dimension "distribution"
            buildConfigField 'boolean', 'IS_GOOGLE', 'true'
            buildConfigField 'boolean', 'IS_HUAWEI', 'true'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        staging {
            initWith buildTypes.release
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'src/android/AndroidManifest.xml'
            java.srcDirs = ['src/main/java', 'src/android/java']
        }

        google {
            java.srcDirs += 'src/google-only/java'
        }
        huawei {
            java.srcDirs += 'src/huawei-only/java'
        }

        universal {
            java.srcDirs = ['src/google/java', 'src/huawei/java', 'src/universal/java']
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true

        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

androidComponents {
    // Only define necessary variants (Skred only has a free tier)
    beforeVariants(
            selector()
                    .withFlavor("product", "skred")
                    .withFlavor("tier", "+")
    ) { variantBuilder ->
        variantBuilder.enable = false
    }
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':twinme-framework')
    implementation project(':webrtc-framework')
    implementation project(':twinlife-framework')

    implementation libs.androidx.core
    implementation libs.androidx.annotation
    implementation libs.androidx.appcompat
    implementation libs.androidx.media
    implementation libs.androidx.exifinterface
    implementation libs.androidx.documentfile
    api libs.androidx.percentlayout

    api libs.androidx.media3.exoplayer
    implementation libs.androidx.media3.ui
    implementation libs.androidx.media3.decoder
    implementation libs.androidx.media3.datasource
    implementation libs.androidx.media3.common
    implementation libs.androidx.media3.session
    implementation libs.androidx.media3.muxer
    implementation libs.androidx.media3.transformer

    implementation libs.zip4j
    implementation libs.glide

    skredImplementation libs.play.services.location

    googleImplementation(libs.firebase.messaging) {
        exclude group: 'com.google.firebase', module: 'firebase-core'
        exclude group: 'com.google.firebase', module: 'firebase-analytics'
        exclude group: 'com.google.firebase', module: 'firebase-measurement-connector'
    }

    universalImplementation(libs.firebase.messaging) {
        exclude group: 'com.google.firebase', module: 'firebase-core'
        exclude group: 'com.google.firebase', module: 'firebase-analytics'
        exclude group: 'com.google.firebase', module: 'firebase-measurement-connector'
    }

    huaweiImplementation libs.huawei.push
    universalImplementation libs.huawei.push

    skredImplementation libs.play.services.location

    coreLibraryDesugaring libs.desugar.jdk.libs

    testImplementation libs.junit.jupiter
    androidTestRuntimeOnly libs.android.test.runner
    androidTestImplementation libs.android.test.core
    androidTestImplementation libs.junit.jupiter.api
    androidTestImplementation libs.junit.jupiter
    androidTestImplementation libs.androidx.test.core
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.test.runner
    androidTestImplementation libs.junit.jupiter.params
}